### development Dockerfile for frontend (run vite dev server)
FROM node:24.11.0-alpine3.21
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN npm install -g pnpm@10.20.0
RUN pnpm install
COPY . ./
EXPOSE 5173
CMD ["pnpm", "dev"]
