### development Dockerfile for frontend (run vite dev server)
FROM node:24.11.0-alpine3.21
WORKDIR /app

# Install Bun
RUN curl -fsSL https://bun.sh/install | bash && \
  mv ~/.bun/bin/bun /usr/local/bin/ && \
  mv ~/.bun/bin/bunx /usr/local/bin/

COPY package.json bun.lockb* ./
RUN bun install
COPY . ./
EXPOSE 5173
CMD ["bun", "--bun", "vite", "--host"]
