### development Dockerfile for frontend (run vite dev server)
FROM node:24-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --silent
COPY . ./
EXPOSE 5173
CMD ["npm", "run", "dev"]
